# Generated by Django 5.2.1 on 2025-05-29 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('versao', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('cor', models.CharField(max_length=30)),
                ('placa', models.CharField(max_length=10)),
                ('usuario', models.CharField(max_length=100)),
                ('data_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
